const models = require("../sequelize/models");

const CLIENTES_TIPO = {
  PERSONA_FISICA: "PERSONA_FISICA",
  PERSONA_JURIDICA: "PERSONA_JURIDICA",
};

const CUENTAS_TIPO = {
  CAJA_DE_AHORRO: "CAJA_DE_AHORRO",
  CUENTA_CORRIENTE: "CUENTA_CORRIENTE",
};

const CONCEPTOS_MOVIMIENTOS = {
  DEPOSITO: "DEPOSITO",
  EXTRACCION: "EXTRACCION",
  COMISION_POR_TRANSACCION: "COMISION_POR_TRANSACCION",
  PAGO_A_PROVEEDOR: "PAGO_A_PROVEEDOR",
  MANTENIMIENTO_DE_CUENTA: "MANTENIMIENTO_DE_CUENTA",
  FONDO_DESCUBIERTO: "FONDO_DESCUBIERTO",
  DINERO_EN_CUENTA: "DINERO_EN_CUENTA",
};

const MOVIMIENTOS_CUENTAS_TIPO = {
  ACREDITA: "ACREDITA",
  DEBITA: "DEBITA",
};

module.exports = {
  CLIENTES_TIPO,
  CUENTAS_TIPO,
  CONCEPTOS_MOVIMIENTOS,
  MOVIMIENTOS_CUENTAS_TIPO,
};
